# Generated by Django 3.2.13 on 2022-04-23 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firmaAdi', models.CharField(max_length=200)),
                ('firmaNo', models.CharField(max_length=200)),
                ('firmaAdresi', models.CharField(max_length=500)),
                ('firmaTel', models.CharField(max_length=50)),
                ('firmaYetkilisi', models.CharField(max_length=50)),
                ('firmaEnlem', models.FloatField(null=True)),
                ('firmaBoylam', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bakim_List',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bakimKayitTarihSaat', models.DateTimeField(auto_now_add=True)),
                ('ilkfoto', models.ImageField(blank=True, upload_to='bakimOnarim/ilkfoto/%Y/%m/%d/')),
                ('sonFoto', models.ImageField(blank=True, upload_to='bakimOnarim/sonFoto/%Y/%m/%d/')),
                ('talepAciklama', models.CharField(max_length=500)),
                ('isAciklama', models.CharField(max_length=500)),
                ('isBaslamaTarihi', models.DateField(blank=True, null=True)),
                ('isBitisTarihi', models.DateField(blank=True, null=True)),
                ('cikisKm', models.IntegerField(blank=True, null=True)),
                ('gelisKm', models.IntegerField(blank=True, null=True)),
                ('durum', models.CharField(default='Tamamlanmadı', max_length=20)),
                ('kullanilanMalzemeler', models.CharField(blank=True, max_length=250, null=True)),
                ('talepEden', models.CharField(max_length=50, null=True)),
                ('isiYapan', models.CharField(max_length=50, null=True)),
                ('sehir', models.CharField(max_length=50, null=True)),
                ('tutanak', models.ImageField(blank=True, upload_to='bakimOnarim/tutanak/%Y/%m/%d/')),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='boApp.firma')),
            ],
        ),
    ]
