# Generated by Django 3.2.13 on 2022-04-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakim_list',
            name='durum',
            field=models.CharField(blank=True, default='Tamamlanmadı', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bakim_list',
            name='isAciklama',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bakim_list',
            name='talepAciklama',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='firmaAdi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='firmaAdresi',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='firmaBoylam',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='firmaEnlem',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='firmaNo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='firmaTel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='firmaYetkilisi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
