# Generated by Django 3.2.13 on 2022-04-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boApp', '0003_auto_20220423_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakim_list',
            name='durum',
            field=models.BooleanField(default=False),
        ),
    ]
